<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StaticCountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'US',
            'alpha3_b' => 'USA',
            'alpha3_t' => 'USA',
            'common_name' => 'United States',
            'native_name' => 'English',
            'exonyms' => json_encode([
                'en' => 'America',
                'fr' => 'États-Unis d\'Amérique',
                'es' => 'Estados Unidos de América',
                'de' => 'Vereinigte Staaten von Amerika',
                'it' => 'Stati Uniti d\'America',
                'pt' => 'Estados Unidos da América',
                'zh' => '美利坚合众国',
                'ar' => 'الولايات المتحدة الأمريكية',
                'ru' => 'Соединенные Штаты Америки',
                'ja' => 'アメリカ合衆国',
                'ko' => '미국',
            ]),
            'region' => 'Americas',
            'subregion' => 'Northern America',
            'calling_code' => '1',
            'capital' => 'Washington, D.C.',
            'population' => '331,449,281',
            'area' => '9,631,418 km²',
            'links' => json_encode([
                'en' => 'United States',
                'fr' => 'États-Unis',
                'es' => 'Estados Unidos',
                'de' => 'Vereinigte Staaten',
                'it' => 'Stati Uniti',
                'pt' => 'Estados Unidos',
                'zh' => '美国',
                'ar' => 'الولايات المتحدة',
                'ru' => 'Соединенные Штаты',
                'ja' => 'アメリカ合衆国',
                'ko' => '미국',
            ]),
            'tlds' => json_encode(['.us']),
            'membership' => json_encode(['UN', 'NATO', 'G7', 'G20']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => '123 Main St',
                'city' => 'Anytown',
                'state' => 'CA',
                'postal_code' => '12345',
                'country' => 'United States',
            ]),
            'postal_code_regex' => '^\d{5}(-\d{4})?$',
            'dialing_prefix' => '1',
            'phone_number_formatting' => json_encode([
                'national' => '1 (555) 123-4567',
                'international' => '+1 555 123 4567',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => '$',
                'name' => 'US Dollar',
                'code' => 'USD',
                'fraction' => '2',
            ]),
        ]);

        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'CA',
            'alpha3_b' => 'CAN',
            'alpha3_t' => 'CAN',
            'common_name' => 'Canada',
            'native_name' => 'English',
            'exonyms' => json_encode([
                'en' => 'Canada',
                'fr' => 'Canada',
                'es' => 'Canadá',
                'de' => 'Kanada',
                'it' => 'Canada',
                'pt' => 'Canadá',
                'zh' => '加拿大',
                'ar' => 'كندا',
                'ru' => 'Канада',
                'ja' => 'カナダ',
                'ko' => '캐나다',
            ]),
            'region' => 'Americas',
            'subregion' => 'Northern America',
            'calling_code' => '1',
            'capital' => 'Ottawa',
            'population' => '37,745,477',
            'area' => '10,085,000 km²',
            'links' => json_encode([
                'en' => 'Canada',
                'fr' => 'Canada',
                'es' => 'Canadá',
                'de' => 'Kanada',
                'it' => 'Canada',
                'pt' => 'Canadá',
                'zh' => '加拿大',
                'ar' => 'كندا',
                'ru' => 'Канада',
                'ja' => 'カナダ',
                'ko' => '캐나다',
            ]),
            'tlds' => json_encode(['.ca']),
            'membership' => json_encode(['UN', 'NATO', 'G7', 'G20']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => '123 Main St',
                'city' => 'Anytown',
                'province' => 'ON',
                'postal_code' => 'A1A 1A1',
                'country' => 'Canada',
            ]),
            'postal_code_regex' => '^[A-Z]\d[A-Z] *\d[A-Z]\d$',
            'dialing_prefix' => '1',
            'phone_number_formatting' => json_encode([
                'national' => '1 (555) 123-4567',
                'international' => '+1 555 123 4567',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => '$',
                'name' => 'Canadian Dollar',
                'code' => 'CAD',
                'fraction' => '2',
            ]),
        ]);

        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'MX',
            'alpha3_b' => 'MEX',
            'alpha3_t' => 'MEX',
            'common_name' => 'Mexico',
            'native_name' => 'Spanish',
            'exonyms' => json_encode([
                'en' => 'Mexico',
                'fr' => 'Mexique',
                'es' => 'México',
                'de' => 'Mexiko',
                'it' => 'Messico',
                'pt' => 'México',
                'zh' => '墨西哥',
                'ar' => 'المكسيك',
                'ru' => 'Мексика',
                'ja' => 'メキシコ',
                'ko' => '멕시코',
            ]),
            'region' => 'Americas',
            'subregion' => 'Northern America',
            'calling_code' => '52',
            'capital' => 'Mexico City',
            'population' => '130,759,074',
            'area' => '2,142,500 km²',
            'links' => json_encode([
                'en' => 'Mexico',
                'fr' => 'Mexique',
                'es' => 'México',
                'de' => 'Mexiko',
                'it' => 'Messico',
                'pt' => 'México',
                'zh' => '墨西哥',
                'ar' => 'المكسيك',
                'ru' => 'Мексика',
                'ja' => 'メキシコ',
                'ko' => '멕시코',
            ]),
            'tlds' => json_encode(['.mx']),
            'membership' => json_encode(['UN', 'OECD', 'USMCA']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => 'Calle 123',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'postal_code' => '12345',
                'country' => 'Mexico',
            ]),
            'postal_code_regex' => '^\d{5}$',
            'dialing_prefix' => '52',
            'phone_number_formatting' => json_encode([
                'national' => '55 1234 5678',
                'international' => '+52 55 1234 5678',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => '$',
                'name' => 'Mexican Peso',
                'code' => 'MXN',
                'fraction' => '2',
            ]),
        ]);

        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'BR',
            'alpha3_b' => 'BRA',
            'alpha3_t' => 'BRA',
            'common_name' => 'Brazil',
            'native_name' => 'Portuguese',
            'exonyms' => json_encode([
                'en' => 'Brazil',
                'fr' => 'Brésil',
                'es' => 'Brasil',
                'de' => 'Brasilien',
                'it' => 'Brasile',
                'pt' => 'Brasil',
                'zh' => '巴西',
                'ar' => 'البرازيل',
                'ru' => 'Бразилия',
                'ja' => 'ブラジル',
                'ko' => '브라질',
            ]),
            'region' => 'Americas',
            'subregion' => 'South America',
            'calling_code' => '55',
            'capital' => 'Brasília',
            'population' => '213,691,000',
            'area' => '8,514,877 km²',
            'links' => json_encode([
                'en' => 'Brazil',
                'fr' => 'Brésil',
                'es' => 'Brasil',
                'de' => 'Brasilien',
                'it' => 'Brasile',
                'pt' => 'Brasil',
                'zh' => '巴西',
                'ar' => 'البرازيل',
                'ru' => 'Бразилия',
                'ja' => 'ブラジル',
                'ko' => '브라질',
            ]),
            'tlds' => json_encode(['.br']),
            'membership' => json_encode(['UN', 'Mercosur', 'BRICS']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => 'Rua 123',
                'city' => 'Brasília',
                'state' => 'DF',
                'postal_code' => '70000-000',
                'country' => 'Brazil',
            ]),
            'postal_code_regex' => '^\d{5}-\d{3}$',
            'dialing_prefix' => '55',
            'phone_number_formatting' => json_encode([
                'national' => '61 1234 5678',
                'international' => '+55 61 1234 5678',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => 'R$',
                'name' => 'Brazilian Real',
                'code' => 'BRL',
                'fraction' => '2',
            ]),
        ]);

        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'RU',
            'alpha3_b' => 'RUS',
            'alpha3_t' => 'RUS',
            'common_name' => 'Russia',
            'native_name' => 'Russian',
            'exonyms' => json_encode([
                'en' => 'Russia',
                'fr' => 'Russie',
                'es' => 'Rusia',
                'de' => 'Russland',
                'it' => 'Russia',
                'pt' => 'Rússia',
                'zh' => '俄罗斯',
                'ar' => 'روسيا',
                'ru' => 'Россия',
                'ja' => 'ロシア',
                'ko' => '러시아',
            ]),
            'region' => 'Europe',
            'subregion' => 'Eastern Europe',
            'calling_code' => '7',
            'capital' => 'Moscow',
            'population' => '145,934,027',
            'area' => '17,125,200 km²',
            'links' => json_encode([
                'en' => 'Russia',
                'fr' => 'Russie',
                'es' => 'Rusia',
                'de' => 'Russland',
                'it' => 'Russia',
                'pt' => 'Rússia',
                'zh' => '俄罗斯',
                'ar' => 'روسيا',
                'ru' => 'Россия',
                'ja' => 'ロシア',
                'ko' => '러시아',
            ]),
            'tlds' => json_encode(['.ru', '.рф']),
            'membership' => json_encode(['UN', 'CIS', 'EAEU']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => 'Улица 123',
                'city' => 'Москва',
                'postal_code' => '123456',
                'country' => 'Russia',
            ]),
            'postal_code_regex' => '^\d{6}$',
            'dialing_prefix' => '7',
            'phone_number_formatting' => json_encode([
                'national' => '8 (555) 123-4567',
                'international' => '+7 555 123 4567',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => '₽',
                'name' => 'Russian Ruble',
                'code' => 'RUB',
                'fraction' => '2',
            ]),
        ]);

        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'CN',
            'alpha3_b' => 'CHN',
            'alpha3_t' => 'CHN',
            'common_name' => 'China',
            'native_name' => 'Chinese',
            'exonyms' => json_encode([
                'en' => 'China',
                'fr' => 'Chine',
                'es' => 'China',
                'de' => 'China',
                'it' => 'Cina',
                'pt' => 'China',
                'zh' => '中国',
                'ar' => 'الصين',
                'ru' => 'Китай',
                'ja' => '中国',
                'ko' => '중국',
            ]),
            'region' => 'Asia',
            'subregion' => 'Eastern Asia',
            'calling_code' => '86',
            'capital' => 'Beijing',
            'population' => '1,439,323,776',
            'area' => '9,596,961 km²',
            'links' => json_encode([
                'en' => 'China',
                'fr' => 'Chine',
                'es' => 'China',
                'de' => 'China',
                'it' => 'Cina',
                'pt' => 'China',
                'zh' => '中国',
                'ar' => 'الصين',
                'ru' => 'Китай',
                'ja' => '中国',
                'ko' => '중국',
            ]),
            'tlds' => json_encode(['.cn']),
            'membership' => json_encode(['UN', 'BRICS', 'SCO']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => '街道123号',
                'city' => '北京',
                'postal_code' => '100000',
                'country' => 'China',
            ]),
            'postal_code_regex' => '^\d{6}$',
            'dialing_prefix' => '86',
            'phone_number_formatting' => json_encode([
                'national' => '10 1234 5678',
                'international' => '+86 10 1234 5678',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => '¥',
                'name' => 'Renminbi',
                'code' => 'CNY',
                'fraction' => '2',
            ]),
        ]);

        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'JP',
            'alpha3_b' => 'JPN',
            'alpha3_t' => 'JPN',
            'common_name' => 'Japan',
            'native_name' => 'Japanese',
            'exonyms' => json_encode([
                'en' => 'Japan',
                'fr' => 'Japon',
                'es' => 'Japón',
                'de' => 'Japan',
                'it' => 'Giappone',
                'pt' => 'Japão',
                'zh' => '日本',
                'ar' => 'اليابان',
                'ru' => 'Япония',
                'ja' => '日本',
                'ko' => '일본',
            ]),
            'region' => 'Asia',
            'subregion' => 'Eastern Asia',
            'calling_code' => '81',
            'capital' => 'Tokyo',
            'population' => '127,103,388',
            'area' => '377,944 km²',
            'links' => json_encode([
                'en' => 'Japan',
                'fr' => 'Japon',
                'es' => 'Japón',
                'de' => 'Japan',
                'it' => 'Giappone',
                'pt' => 'Japão',
                'zh' => '日本',
                'ar' => 'اليابان',
                'ru' => 'Япония',
                'ja' => '日本',
                'ko' => '일본',
            ]),
            'tlds' => json_encode(['.jp']),
            'membership' => json_encode(['UN', 'G7', 'G20']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => '通り123号',
                'city' => '東京',
                'postal_code' => '100-0001',
                'country' => 'Japan',
            ]),
            'postal_code_regex' => '^\d{3}-\d{4}$',
            'dialing_prefix' => '81',
            'phone_number_formatting' => json_encode([
                'national' => '03 1234 5678',
                'international' => '+81 3 1234 5678',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => '¥',
                'name' => 'Yen',
                'code' => 'JPY',
                'fraction' => '0',
            ]),
        ]);

        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'DE',
            'alpha3_b' => 'DEU',
            'alpha3_t' => 'DEU',
            'common_name' => 'Germany',
            'native_name' => 'German',
            'exonyms' => json_encode([
                'en' => 'Germany',
                'fr' => 'Allemagne',
                'es' => 'Alemania',
                'de' => 'Deutschland',
                'it' => 'Germania',
                'pt' => 'Alemanha',
                'zh' => '德国',
                'ar' => 'ألمانيا',
                'ru' => 'Германия',
                'ja' => 'ドイツ',
                'ko' => '독일',
            ]),
            'region' => 'Europe',
            'subregion' => 'Western Europe',
            'calling_code' => '49',
            'capital' => 'Berlin',
            'population' => '83,251,851',
            'area' => '357,022 km²',
            'links' => json_encode([
                'en' => 'Germany',
                'fr' => 'Allemagne',
                'es' => 'Alemania',
                'de' => 'Deutschland',
                'it' => 'Germania',
                'pt' => 'Alemanha',
                'zh' => '德国',
                'ar' => 'ألمانيا',
                'ru' => 'Германия',
                'ja' => 'ドイツ',
                'ko' => '독일',
            ]),
            'tlds' => json_encode(['.de']),
            'membership' => json_encode(['UN', 'EU', 'NATO', 'G7', 'G20']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => 'Straße 123',
                'city' => 'Berlin',
                'postal_code' => '10115',
                'country' => 'Germany',
            ]),
            'postal_code_regex' => '^\d{5}$',
            'dialing_prefix' => '49',
            'phone_number_formatting' => json_encode([
                'national' => '30 1234 5678',
                'international' => '+49 30 1234 5678',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => '€',
                'name' => 'Euro',
                'code' => 'EUR',
                'fraction' => '2',
            ]),

        ]);

        \App\Builder\Locale\Models\StaticCountry::create([
            'alpha2' => 'FR',
            'alpha3_b' => 'FRA',
            'alpha3_t' => 'FRA',
            'common_name' => 'France',
            'native_name' => 'French',
            'exonyms' => json_encode([
                'en' => 'France',
                'fr' => 'France',
                'es' => 'Francia',
                'de' => 'Frankreich',
                'it' => 'Francia',
                'pt' => 'França',
                'zh' => '法国',
                'ar' => 'فرنسا',
                'ru' => 'Франция',
                'ja' => 'フランス',
                'ko' => '프랑스',
            ]),
            'region' => 'Europe',
            'subregion' => 'Western Europe',
            'calling_code' => '33',
            'capital' => 'Paris',
            'population' => '67,221,857',
            'area' => '643,801 km²',
            'links' => json_encode([
                'en' => 'France',
                'fr' => 'France',
                'es' => 'Francia',
                'de' => 'Frankreich',
                'it' => 'Francia',
                'pt' => 'França',
                'zh' => '法国',
                'ar' => 'فرنسا',
                'ru' => 'Франция',
                'ja' => 'フランス',
                'ko' => '프랑스',
            ]),
            'tlds' => json_encode(['.fr']),
            'membership' => json_encode(['UN', 'EU', 'NATO', 'G7', 'G20']),
            'embargo' => 'Open',
            'embargo_data' => 'No embargo',
            'address_format' => json_encode([
                'street' => 'Rue 123',
                'city' => 'Paris',
                'postal_code' => '75001',
                'country' => 'France',
            ]),
            'postal_code_regex' => '^\d{5}$',
            'dialing_prefix' => '33',
            'phone_number_formatting' => json_encode([
                'national' => '1 42 42 42 42',
                'international' => '+33 1 42 42 42 42',
            ]),
            'date_format' => 'Y-m-d',
            'currency_format' => json_encode([
                'symbol' => '€',
                'name' => 'Euro',
                'code' => 'EUR',
                'fraction' => '2',
            ]),
        ]);
    }
}
