<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StaticLanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Locale\Models\StaticLanguage::insert([
            [
                'alpha2' => 'en',
                'alpha3_b' => 'eng',
                'alpha3_t' => 'eng',
                'common_name' => 'English',
                'direction' => 'LTR',
                'exonyms' => [
                    'fr' => 'Anglais',
                    'es' => 'Inglés',
                    'de' => 'Englisch',
                    'it' => 'Inglese',
                    'pt' => 'Inglês',
                    'zh' => '',
                ],
                'native_name' => 'English',
                'script' => 'Latin',
            ],
            [
                'alpha2' => 'fr',
                'alpha3_b' => 'fra',
                'alpha3_t' => 'fra',
                'common_name' => 'French',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'French',
                    'es' => 'Francés',
                    'de' => 'Französisch',
                    'it' => 'Francese',
                    'pt' => 'Francês',
                    'zh' => '',
                ]),
                'native_name' => 'Français',
                'script' => 'Latin',
            ],
            [
                'alpha2' => 'es',
                'alpha3_b' => 'spa',
                'alpha3_t' => 'spa',
                'common_name' => 'Spanish',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'Spanish',
                    'fr' => 'Espagnol',
                    'de' => 'Spanisch',
                    'it' => 'Spagnolo',
                    'pt' => 'Espanhol',
                    'zh' => '',
                ]),
                'native_name' => 'Español',
                'script' => 'Latin',
            ],
            [
                'alpha2' => 'de',
                'alpha3_b' => 'ger',
                'alpha3_t' => 'ger',
                'common_name' => 'German',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'German',
                    'fr' => 'Allemand',
                    'es' => 'Alemán',
                    'it' => 'Tedesco',
                    'pt' => 'Alemão',
                    'zh' => '',
                ]),
                'native_name' => 'Deutsch',
                'script' => 'Latin',
            ],
            [
                'alpha2' => 'it',
                'alpha3_b' => 'ita',
                'alpha3_t' => 'ita',
                'common_name' => 'Italian',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'Italian',
                    'fr' => 'Italien',
                    'es' => 'Italiano',
                    'de' => 'Italienisch',
                    'pt' => 'Italiano',
                    'zh' => '',
                ]),
                'native_name' => 'Italiano',
                'script' => 'Latin',
            ],
            [
                'alpha2' => 'pt',
                'alpha3_b' => 'por',
                'alpha3_t' => 'por',
                'common_name' => 'Portuguese',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'Portuguese',
                    'fr' => 'Portugais',
                    'es' => 'Portugués',
                    'de' => 'Portugiesisch',
                    'it' => 'Portoghese',
                    'zh' => '',
                ]),
                'native_name' => 'Português',
                'script' => 'Latin',
            ],
            [
                'alpha2' => 'zh',
                'alpha3_b' => 'zho',
                'alpha3_t' => 'zho',
                'common_name' => 'Chinese',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'Chinese',
                    'fr' => 'Chinois',
                    'es' => 'Chino',
                    'de' => 'Chinesisch',
                    'it' => 'Cinese',
                    'pt' => 'Chinês',
                ]),
                'native_name' => '中文',
                'script' => 'Han',
            ],
            [
                'alpha2' => 'ar',
                'alpha3_b' => 'ara',
                'alpha3_t' => 'ara',
                'common_name' => 'Arabic',
                'direction' => 'RTL',
                'exonyms' => json_encode([
                    'en' => 'Arabic',
                    'fr' => 'Arabe',
                    'es' => 'Árabe',
                    'de' => 'Arabisch',
                    'it' => 'Arabo',
                    'pt' => 'Árabe',
                    'zh' => '',
                ]),
                'native_name' => 'العربية',
                'script' => 'Arabic',
            ],
            [
                'alpha2' => 'ru',
                'alpha3_b' => 'rus',
                'alpha3_t' => 'rus',
                'common_name' => 'Russian',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'Russian',
                    'fr' => 'Russe',
                    'es' => 'Ruso',
                    'de' => 'Russisch',
                    'it' => 'Russo',
                    'pt' => 'Russo',
                    'zh' => '',
                ]),
                'native_name' => 'Русский',
                'script' => 'Cyrillic',
            ],
            [
                'alpha2' => 'ja',
                'alpha3_b' => 'jpn',
                'alpha3_t' => 'jpn',
                'common_name' => 'Japanese',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'Japanese',
                    'fr' => 'Japonais',
                    'es' => 'Japonés',
                    'de' => 'Japanisch',
                    'it' => 'Giapponese',
                    'pt' => 'Japonês',
                    'zh' => '',
                ]),
                'native_name' => '日本語',
                'script' => 'Han',
            ],
            [
                'alpha2' => 'ko',
                'alpha3_b' => 'kor',
                'alpha3_t' => 'kor',
                'common_name' => 'Korean',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'Korean',
                    'fr' => 'Coréen',
                    'es' => 'Coreano',
                    'de' => 'Koreanisch',
                    'it' => 'Coreano',
                    'pt' => 'Coreano',
                    'zh' => '',
                ]),
                'native_name' => '한국어',
                'script' => 'Hangul',
            ],
            [
                'alpha2' => 'hi',
                'alpha3_b' => 'hin',
                'alpha3_t' => 'hin',
                'common_name' => 'Hindi',
                'direction' => 'LTR',
                'exonyms' => json_encode([
                    'en' => 'Hindi',
                    'fr' => 'Hindi',
                    'es' => 'Hindi',
                    'de' => 'Hindi',
                    'it' => 'Hindi',
                    'pt' => 'Hindi',
                    'zh' => '',
                ]),
                'native_name' => 'हिन्दी',
                'script' => 'Devanagari',
            ],
        ]);
    }
}
