 <?php

/*

- Package
    - Fields
        - Name
        - Description
        - Version
        - License
        - Author
        - Website
        - Status
            - Draft
            - Built
            - Installed
            - Active
    - Actions
        - Create
        - View
        - Edit
        - Delete
        - Build
        - Install
        - Activate - per entity per panel
    - Entity
        - Fields
            - Template - Select, preset preselects features
                - Simple
                - Item
                - Taxonomy
            - Name
            - Description
            - Package (or App) - Select
            - Features - https://filamentphp.com/docs/3.x/forms/fields/checkbox-list
                - View
                - Create
                - Edit
                - Delete
                - Soft Delete
                - Publish
                - Author
                - Widgets
            - Taxonomies - https://github.com/lucasgiovanny/filament-multiselect-two-sides
                - Categories
                - Tags
                - ...
            - Tabs - https://github.com/lucasgiovanny/filament-multiselect-two-sides
            - Fields - https://filamentphp.com/docs/3.x/forms/fields/repeater or https://filamentphp.com/docs/3.x/forms/fields/builder
                - Title
                - Type - Select
                    - String
                    - Text
                    - Image
                    - ...
                - Features - https://filamentphp.com/docs/3.x/forms/fields/checkbox-list
                    - View
                    - Create
                    - Edit
                    - Delete
                    - Soft Delete
                    - Publish
    - Components - used by fields - name of the part(s) to render
        - String
        - Text
        - Image
        - ...

*/
