/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        path.resolve(__dirname, "./resources/**/*.blade.php"),
        path.resolve(__dirname, "./resources/**/*.js"),
        path.resolve(__dirname, "./resources/**/*.vue"),
        path.resolve(__dirname, "./packages/**/*.blade.php"),
        path.resolve(
            __dirname,
            "./packages/featherlight/resources/**/*.blade.php"
        ),
    ],
    safelist: [
        "text-center",
        "text-4xl",
        "text-5xl",
        "text-base",
        "text-lg",
        "text-xl",
        "text-3xl",
        "font-extrabold",
        "font-medium",
        "font-semibold",
        "text-gray-900",
        "text-indigo-600",
        "text-gray-500",
        "text-white",
        "bg-indigo-600",
        "bg-indigo-700",
        "bg-white",
        "bg-gray-50",
        "bg-indigo-500",
        "mt-3",
        "mt-5",
        "mt-8",
        "mt-2",
        "mt-4",
        "mt-10",
        "max-w-md",
        "max-w-3xl",
        "max-w-7xl",
        "max-w-2xl",
        "mx-auto",
        "px-4",
        "py-3",
        "py-4",
        "py-12",
        "flex",
        "items-center",
        "justify-center",
        "rounded-md",
        "shadow",
        "space-y-10",
        "w-full",
        "h-12",
        "w-12",
        "h-6",
        "w-6",
        "block",
        "relative",
        "absolute",
        "sm:text-5xl",
        "sm:text-lg",
        "sm:flex",
        "sm:justify-center",
        "sm:px-6",
        "sm:mt-0",
        "sm:ml-3",
        "md:mt-5",
        "md:text-xl",
        "md:max-w-3xl",
        "md:py-4",
        "md:text-lg",
        "md:px-10",
        "md:space-y-0",
        "md:grid",
        "md:grid-cols-2",
        "md:gap-x-8",
        "md:gap-y-10",
        "lg:px-8",
        "lg:text-center",
        "lg:mx-auto",
        "hover:bg-indigo-700",
        "hover:bg-gray-50",
    ],
    theme: {
        extend: {
            container: {
                center: true,
                padding: {
                    DEFAULT: "1rem",
                    sm: "2rem",
                    lg: "4rem",
                    xl: "5rem",
                    "2xl": "6rem",
                },
                screens: {
                    sm: "640px",
                    md: "768px",
                    lg: "1024px",
                    xl: "1280px",
                    "2xl": "1536px",
                },
            },
            colors: {
                gray: {
                    50: "#f9fafb",
                    100: "#f3f4f6",
                    200: "#e5e7eb",
                    300: "#d1d5db",
                    400: "#9ca3af",
                    500: "#6b7280",
                    600: "#4b5563",
                    700: "#374151",
                    800: "#1f2937",
                    900: "#111827",
                },
                indigo: {
                    50: "#eef2ff",
                    100: "#e0e7ff",
                    200: "#c7d2fe",
                    300: "#a5b4fc",
                    400: "#818cf8",
                    500: "#6366f1",
                    600: "#4f46e5",
                    700: "#4338ca",
                    800: "#3730a3",
                    900: "#312e81",
                },
            },
        },
    },
    plugins: [],
};
