<?php

declare(strict_types=1);

namespace Moox\Zugferd;

use horstoeko\zugferd\ZugferdDocumentBuilder;
use horstoeko\zugferd\ZugferdDocumentPdfMerger;
use horstoeko\zugferd\ZugferdProfiles;
use Illuminate\Support\Str;
use Moox\Zugferd\Contracts\ZugferdAddress;
use Moox\Zugferd\Contracts\ZugferdAllowanceCharge;
use Moox\Zugferd\Contracts\ZugferdInvoice;
use Moox\Zugferd\Exceptions\IncompleteInvoiceException;
use Symfony\Component\Process\Process;

class ZugferdConverter
{
    private const PROFILE_MAP = [
        'MINIMUM' => ZugferdProfiles::PROFILE_MINIMUM,
        'BASIC' => ZugferdProfiles::PROFILE_BASIC,
        'EN16931' => ZugferdProfiles::PROFILE_EN16931,
        'EXTENDED' => ZugferdProfiles::PROFILE_EXTENDED,
        'XRECHNUNG' => ZugferdProfiles::PROFILE_XRECHNUNG_3,
    ];

    public function convert(ZugferdInvoice $invoice): string
    {
        $document = $this->buildDocument($invoice);

        return $this->getContentSafely($document);
    }

    public function convertToFile(ZugferdInvoice $invoice, ?string $outputPath = null): string
    {
        $outputPath ??= config('zugferd.output_path', storage_path('app/private/zugferd'));

        if (! is_dir($outputPath)) {
            mkdir($outputPath, 0755, true);
        }

        $filename = sprintf('%s/%s.xml', rtrim($outputPath, '/'), $invoice->invoiceNumber);

        $xml = $this->convert($invoice);
        file_put_contents($filename, $xml);

        return $filename;
    }

    /**
     * Merge ZUGFeRD XML into an existing PDF to create a PDF/A-3 compliant file.
     *
     * @param  string  $pdfPath  Absolute path to the original invoice PDF
     * @param  string  $xml  The ZUGFeRD XML string (already generated by convertToXml())
     * @return string The binary content of the resulting ZUGFeRD PDF
     */
    public function mergePdfWithXml(string $pdfPath, string $xml): string
    {
        $tempDir = rtrim(sys_get_temp_dir(), '/');
        $uid = Str::uuid()->toString();
        $decryptedPath = "{$tempDir}/{$uid}_decrypted.pdf";
        $mergedPath = "{$tempDir}/{$uid}_merged.pdf";
        $encryptedPath = "{$tempDir}/{$uid}_encrypted.pdf";
        $passwordRaw = config('mail-inbox.zugferd.pdf_password');
        $password = is_string($passwordRaw) && $passwordRaw !== '' ? $passwordRaw : null;

        try {
            $decryptCmd = array_values(array_filter([
                'qpdf',
                '--decrypt',
                $password !== null ? "--password={$password}" : null,
                $pdfPath,
                $decryptedPath,
            ]));

            $decryptProcess = new Process($decryptCmd);
            $decryptProcess->run();

            $sourcePath = ($decryptProcess->isSuccessful() && is_file($decryptedPath))
                ? $decryptedPath
                : $pdfPath;

            $merger = new ZugferdDocumentPdfMerger($xml, $sourcePath);
            $merger->generateDocument()->saveDocument($mergedPath);

            $mergedContent = file_get_contents($mergedPath);
            if ($mergedContent === false) {
                throw new \RuntimeException('Failed to read generated ZUGFeRD PDF from temp file.');
            }

            if ($password !== null && is_file($mergedPath)) {
                $encryptCmd = [
                    'qpdf',
                    '--encrypt',
                    '',
                    $password,
                    '128',
                    '--print=full',
                    '--modify=none',
                    '--',
                    $mergedPath,
                    $encryptedPath,
                ];

                $encryptProcess = new Process($encryptCmd);
                $encryptProcess->run();

                if ($encryptProcess->isSuccessful() && is_file($encryptedPath)) {
                    $encryptedContent = file_get_contents($encryptedPath);
                    if ($encryptedContent === false) {
                        throw new \RuntimeException('Failed to read re-encrypted ZUGFeRD PDF from temp file.');
                    }

                    return $encryptedContent;
                }
            }

            return $mergedContent;
        } finally {
            foreach ([$decryptedPath, $mergedPath, $encryptedPath] as $tmp) {
                if (is_file($tmp)) {
                    @unlink($tmp);
                }
            }
        }
    }

    private function getContentSafely(ZugferdDocumentBuilder $document): string
    {
        $xml = '';

        $previousHandler = set_error_handler(function (int $severity, string $message) use (&$previousHandler): bool {
            if (str_contains($message, 'supplied resource is not a valid stream resource')) {
                return true;
            }

            return $previousHandler ? $previousHandler($severity, $message) : false;
        });

        try {
            $xml = $document->getContent();
        } catch (\TypeError $e) {
            if (! str_contains($e->getMessage(), 'stream resource')) {
                throw $e;
            }
        } finally {
            restore_error_handler();
        }

        return $xml;
    }

    private function buildDocument(ZugferdInvoice $invoice): ZugferdDocumentBuilder
    {
        $profileKey = config('zugferd.profile', 'EN16931');
        $profile = self::PROFILE_MAP[$profileKey] ?? ZugferdProfiles::PROFILE_EN16931;

        $document = ZugferdDocumentBuilder::createNew($profile);

        $this->setDocumentInfo($document, $invoice);
        $this->setSeller($document, $invoice);
        $this->setBuyer($document, $invoice);
        $this->setPaymentInfo($document, $invoice);
        $this->addLineItems($document, $invoice);
        $this->addAllowanceCharges($document, $invoice);
        $this->setTotals($document, $invoice);

        return $document;
    }

    // ─── Document Info ───────────────────────────────────────────

    private function setDocumentInfo(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $typeCode = str_contains(mb_strtolower($invoice->documentType), 'gutschrift') ? '381' : '380';

        $doc->setDocumentInformation(
            $invoice->invoiceNumber,
            $typeCode,
            \DateTime::createFromFormat('Y-m-d', $invoice->invoiceDate) ?: new \DateTime,
            $invoice->currency,
        );

        $doc->setDocumentBusinessProcess('urn:fdc:peppol.eu:2017:poacc:billing:01:1.0');
        $buyerRef = $invoice->customerReference ?: $invoice->customerNumber ?: 'N/A';
        $doc->setDocumentBuyerReference($buyerRef);
    }

    // ─── Seller (BG-4) ──────────────────────────────────────────

    private function setSeller(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $doc->setDocumentSeller($invoice->supplierName);

        if ($invoice->supplierAddress === null) {
            throw new IncompleteInvoiceException('Missing required field: supplierAddress (BG-5 seller postal address).');
        }

        [$s1, $s2, $s3] = $this->buildAddressLines($invoice->supplierAddress);
        $doc->setDocumentSellerAddress(
            $s1,
            $s2,
            $s3,
            $invoice->supplierAddress->zip ?? '',
            $invoice->supplierAddress->city ?? '',
            $invoice->supplierAddress->country ?? '',
        );

        if ($invoice->supplierEmail === null || trim($invoice->supplierEmail) === '') {
            throw new IncompleteInvoiceException('Missing required field: supplierEmail (BT-34 seller electronic address).');
        }

        $doc->setDocumentSellerContact(
            $invoice->agent ?? '',
            '',
            $invoice->supplierPhone ?? '',
            '',
            $invoice->supplierEmail,
        );

        $doc->setDocumentSellerCommunication('EM', $invoice->supplierEmail);

        if ($invoice->supplierVatId) {
            // Remove spaces from VAT ID (DE 123 456 789 → DE123456789)
            $vatId = preg_replace('/\s+/', '', $invoice->supplierVatId);
            $doc->addDocumentSellerTaxRegistration('VA', $vatId);
        }
        if ($invoice->supplierTaxNumber) {
            $doc->addDocumentSellerTaxRegistration('FC', $invoice->supplierTaxNumber);
        }
    }

    // ─── Buyer (BG-7) ───────────────────────────────────────────

    private function setBuyer(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $doc->setDocumentBuyer($invoice->customerName);

        if ($invoice->customerAddress === null) {
            throw new IncompleteInvoiceException('Missing required field: customerAddress (BG-8 buyer postal address).');
        }

        [$b1, $b2, $b3] = $this->buildAddressLines($invoice->customerAddress);
        $doc->setDocumentBuyerAddress(
            $b1,
            $b2,
            $b3,
            $invoice->customerAddress->zip ?? '',
            $invoice->customerAddress->city ?? '',
            $invoice->customerAddress->country ?? '',
        );

        if ($invoice->customerVatId) {
            $doc->addDocumentBuyerTaxRegistration('VA', $invoice->customerVatId);
        }

        $doc->setDocumentBuyerCommunication('EM', $invoice->customerNumber ?: 'N/A');
    }

    // ─── Payment (BG-16) ────────────────────────────────────────

    private function setPaymentInfo(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        if ($invoice->bankAccounts === []) {
            throw new IncompleteInvoiceException('Missing required field: bankAccounts (at least one payment means bank account).');
        }

        foreach ($invoice->bankAccounts as $account) {
            $iban = trim($account->iban);
            if ($iban === '') {
                throw new IncompleteInvoiceException('Missing required field: bankAccounts[].iban (payment means payee IBAN).');
            }

            $doc->addDocumentPaymentMean(
                $invoice->paymentMeansCode ?? '58',
                null,
                null,
                null,
                null,
                null,
                $iban,
                $account->accountHolder ?? $invoice->supplierName,
                null,
                $account->bic,
            );
        }

        // Payment terms
        if ($invoice->dueDate) {
            $dueDate = \DateTime::createFromFormat('Y-m-d', $invoice->dueDate);
            $termText = $invoice->paymentTerms ?? '';
            if ($invoice->dueDate) {
                $termText .= '; zahlbar ohne Abzug bis zum '.date('d.m.Y', strtotime($invoice->dueDate));
            }
            if ($dueDate) {
                $doc->addDocumentPaymentTerm($termText, $dueDate);
            }
        } elseif ($invoice->paymentTerms) {
            $doc->addDocumentPaymentTerm($invoice->paymentTerms);
        }
    }

    // ─── Line Items ──────────────────────────────────────────────

    private function addLineItems(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        foreach ($invoice->lines as $line) {
            $doc->addNewPosition((string) $line->position);
            $doc->setDocumentPositionProductDetails(
                $line->description,
                $line->descriptionDetail ?? '',
                $line->articleNumber,
            );
            $doc->setDocumentPositionNetPrice($line->unitPrice);
            $doc->setDocumentPositionQuantity(
                $line->quantity,
                $this->mapUnitCode($line->unit),
            );

            // Line total WITHOUT surcharges (surcharges go to document level)
            $doc->setDocumentPositionLineSummation($line->lineTotal);

            $doc->addDocumentPositionTax('S', 'VAT', $invoice->vatRate);
        }
    }

    // ─── Allowances & Charges (BG-20/BG-21) ─────────────────────

    private function addAllowanceCharges(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        foreach ($this->collectAllowanceCharges($invoice) as $item) {
            if ($item->amount <= 0) {
                continue;
            }

            $doc->addDocumentAllowanceCharge(
                $item->amount,
                $item->isCharge,
                'S',
                'VAT',
                $invoice->vatRate,
                null,
                null,
                null,
                null,
                null,
                $item->reasonCode,
                $item->reasonText,
            );
        }
    }

    /**
     * @return list<ZugferdAllowanceCharge>
     */
    private function collectAllowanceCharges(ZugferdInvoice $invoice): array
    {
        $items = $invoice->allowanceCharges;

        foreach ($invoice->lines as $line) {
            foreach ($line->allowanceCharges as $lineItem) {
                $items[] = $lineItem;
            }
        }

        return $items;
    }

    // ─── Totals (BG-22) ─────────────────────────────────────────

    private function setTotals(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $lineTotalSum = 0;
        foreach ($invoice->lines as $line) {
            $lineTotalSum += $line->lineTotal;
        }

        $chargeTotal = 0.0;
        $allowanceTotal = 0.0;

        foreach ($this->collectAllowanceCharges($invoice) as $item) {
            if ($item->amount <= 0) {
                continue;
            }

            if ($item->isCharge) {
                $chargeTotal += $item->amount;
            } else {
                $allowanceTotal += $item->amount;
            }
        }

        $doc->setDocumentSummation(
            $invoice->grossTotal,          // grandTotalAmount (BT-112)
            $invoice->grossTotal,          // duePayableAmount (BT-115)
            $lineTotalSum,                 // lineTotalAmount (BT-106)
            $chargeTotal,                  // chargeTotalAmount (BT-108)
            $allowanceTotal,               // allowanceTotalAmount (BT-107)
            $invoice->netTotal,            // taxBasisTotalAmount (BT-109)
            $invoice->vatAmount,           // taxTotalAmount (BT-110)
        );

        $doc->addDocumentTax('S', 'VAT', $invoice->netTotal, $invoice->vatAmount, $invoice->vatRate);
    }

    // ─── Helper functions ─────────────────────────────────────────

    private function mapUnitCode(string $unit): string
    {
        return match ($unit) {
            'Stück' => 'C62',
            'Meter' => 'MTR',
            'Liter' => 'LTR',
            'kg' => 'KGM',
            'Satz' => 'SET',
            'Pauschal' => 'LS',
            default => 'C62',
        };
    }

    /**
     * @return array{0: ?string, 1: ?string, 2: ?string}
     */
    private function buildAddressLines(ZugferdAddress $address): array
    {
        return [$address->street, $address->addressLine2, $address->addressLine3];
    }
}
