<?php

declare(strict_types=1);

namespace Moox\Zugferd;

use horstoeko\zugferd\ZugferdDocumentBuilder;
use horstoeko\zugferd\ZugferdDocumentPdfMerger;
use horstoeko\zugferd\ZugferdDocumentPdfReader;
use horstoeko\zugferd\ZugferdProfiles;
use Illuminate\Support\Str;
use InvalidArgumentException;
use Moox\Zugferd\Contracts\ZugferdAddress;
use Moox\Zugferd\Contracts\ZugferdAllowanceCharge;
use Moox\Zugferd\Contracts\ZugferdInvoice;
use Moox\Zugferd\Contracts\ZugferdInvoiceLine;
use Moox\Zugferd\Exceptions\IncompleteInvoiceException;
use Moox\Zugferd\Support\FlexibleDateParser;
use Moox\Zugferd\Support\ShipToPartyEquality;
use Symfony\Component\Process\Process;

class ZugferdConverter
{
    /**
     * Default PDF metadata Title template for horstoeko merger (package fallback).
     * sprintf args: invoiceId, docTypeName, seller, date.
     * Produces e.g. "Seller : Invoice 123" (space before colon; horstoeko historical default).
     * Override via config('zugferd.pdf_title_template') / pdf_title_templates.
     */
    public const PDF_TITLE_TEMPLATE = '%3$s : %2$s %1$s';

    private const PROFILE_MAP = [
        'MINIMUM' => ZugferdProfiles::PROFILE_MINIMUM,
        'BASIC' => ZugferdProfiles::PROFILE_BASIC,
        'EN16931' => ZugferdProfiles::PROFILE_EN16931,
        'EXTENDED' => ZugferdProfiles::PROFILE_EXTENDED,
        'XRECHNUNG' => ZugferdProfiles::PROFILE_XRECHNUNG_3,
    ];

    public function convert(ZugferdInvoice $invoice, string $profileKey): string
    {
        $document = $this->buildDocument($invoice, $profileKey);

        return $this->getContentSafely($document);
    }

    public function convertToFile(ZugferdInvoice $invoice, string $profileKey, ?string $outputPath = null): string
    {
        $outputPath ??= config('zugferd.output_path', storage_path('app/private/zugferd'));

        if (! is_dir($outputPath)) {
            mkdir($outputPath, 0755, true);
        }

        $filename = sprintf('%s/%s.xml', rtrim($outputPath, '/'), $invoice->invoiceNumber);

        $xml = $this->convert($invoice, $profileKey);
        file_put_contents($filename, $xml);

        return $filename;
    }

    /**
     * Resolve the PDF Title sprintf template for the given UN/CEFACT document type code.
     * Uses config('zugferd.pdf_title_templates')[$code] when present and non-empty;
     * otherwise config('zugferd.pdf_title_template') / {@see PDF_TITLE_TEMPLATE}.
     */
    public function resolvePdfTitleTemplate(?string $documentTypeCode = null): string
    {
        $default = config('zugferd.pdf_title_template', self::PDF_TITLE_TEMPLATE);
        $default = is_string($default) && $default !== '' ? $default : self::PDF_TITLE_TEMPLATE;

        $code = is_string($documentTypeCode) ? trim($documentTypeCode) : '';
        if ($code === '') {
            return $default;
        }

        $templates = config('zugferd.pdf_title_templates', []);
        if (! is_array($templates)) {
            return $default;
        }

        $template = $templates[$code] ?? null;
        if (! is_string($template) || $template === '') {
            return $default;
        }

        return $template;
    }

    /**
     * Merge ZUGFeRD XML into an existing PDF to create a PDF/A-3 compliant file.
     *
     * @param  string  $pdfPath  Absolute path to the original invoice PDF
     * @param  string  $xml  The ZUGFeRD XML string (already generated by convertToXml())
     * @param  string|null  $documentTypeCode  Optional UN/CEFACT code (e.g. 380/381) for title template selection
     * @return string The binary content of the resulting ZUGFeRD PDF
     */
    public function mergePdfWithXml(string $pdfPath, string $xml, ?string $documentTypeCode = null): string
    {
        $tempDir = rtrim(sys_get_temp_dir(), '/');
        $uid = Str::uuid()->toString();
        $readablePath = "{$tempDir}/{$uid}_readable.pdf";
        $mergedPath = "{$tempDir}/{$uid}_merged.pdf";
        $passwordRaw = config('mail-inbox.zugferd.pdf_password');
        $password = is_string($passwordRaw) && $passwordRaw !== '' ? $passwordRaw : null;

        try {
            $sourcePath = $this->rewritePdfForFpdi($pdfPath, $readablePath, $password);

            $merger = new ZugferdDocumentPdfMerger($xml, $sourcePath);
            $merger->setTitleTemplate($this->resolvePdfTitleTemplate($documentTypeCode));
            $merger->generateDocument()->saveDocument($mergedPath);

            $mergedContent = file_get_contents($mergedPath);
            if ($mergedContent === false) {
                throw new \RuntimeException('Failed to read generated ZUGFeRD PDF from temp file.');
            }

            return $mergedContent;
        } finally {
            foreach ([$readablePath, $mergedPath] as $tmp) {
                if (is_file($tmp)) {
                    @unlink($tmp);
                }
            }
        }
    }

    /**
     * Ghostscript PDF/A output (and some supplier PDFs) uses compressed object
     * streams / xref that the free FPDI parser cannot read. qpdf rewrites them
     * to a classic xref. Exit code 3 is a warning with a usable file.
     */
    private function rewritePdfForFpdi(string $pdfPath, string $outputPath, ?string $password): string
    {
        $command = array_values(array_filter([
            $this->qpdfBinary(),
            '--decrypt',
            '--object-streams=disable',
            $password !== null ? "--password={$password}" : null,
            $pdfPath,
            $outputPath,
        ]));

        $process = new Process($command);
        $process->setTimeout(30);
        $process->run();

        $exitCode = $process->getExitCode();
        $rewritten = is_file($outputPath) && filesize($outputPath) > 8;

        if ($rewritten && ($exitCode === 0 || $exitCode === 3)) {
            return $outputPath;
        }

        return $pdfPath;
    }

    private function qpdfBinary(): string
    {
        foreach ([
            trim((string) config('e-billing.qpdf.binary_path', '')),
            '/opt/homebrew/bin/qpdf',
            '/usr/local/bin/qpdf',
            'qpdf',
        ] as $candidate) {
            if ($candidate !== '' && ($candidate === 'qpdf' || is_executable($candidate))) {
                return $candidate;
            }
        }

        return 'qpdf';
    }

    public function extractXmlFromPdf(string $absolutePdfPath): string
    {
        return ZugferdDocumentPdfReader::getXmlFromFile($absolutePdfPath);
    }

    private function getContentSafely(ZugferdDocumentBuilder $document): string
    {
        $xml = '';

        $previousHandler = set_error_handler(function (int $severity, string $message) use (&$previousHandler): bool {
            if (str_contains($message, 'supplied resource is not a valid stream resource')) {
                return true;
            }

            return $previousHandler ? $previousHandler($severity, $message) : false;
        });

        try {
            $xml = $document->getContent();
        } finally {
            restore_error_handler();
        }

        return $xml;
    }

    private function buildDocument(ZugferdInvoice $invoice, string $profileKey): ZugferdDocumentBuilder
    {
        if (! isset(self::PROFILE_MAP[$profileKey])) {
            throw new InvalidArgumentException(
                "Unknown ZUGFeRD profile [{$profileKey}]. "
                .'Known: '.implode(', ', array_keys(self::PROFILE_MAP)).'.'
            );
        }

        $profile = self::PROFILE_MAP[$profileKey];

        $document = ZugferdDocumentBuilder::createNew($profile);

        $this->setDocumentInfo($document, $invoice);
        $this->setDocumentNotes($document, $invoice);
        $this->setSeller($document, $invoice);
        $this->setBuyer($document, $invoice);
        $this->setTradeReferences($document, $invoice);
        $this->setDelivery($document, $invoice);
        if (trim($invoice->vatCategoryCode) === '') {
            throw new IncompleteInvoiceException('Missing required field: vatCategoryCode (BT-118).');
        }

        $this->setPaymentInfo($document, $invoice);
        $this->addLineItems($document, $invoice, $profileKey);
        $this->addAllowanceCharges($document, $invoice);
        $this->setTotals($document, $invoice);

        return $document;
    }

    // ─── Document Info ───────────────────────────────────────────

    private function setDocumentInfo(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $doc->setDocumentInformation(
            $invoice->invoiceNumber,
            $invoice->documentTypeCode,
            \DateTime::createFromFormat('Y-m-d', $invoice->invoiceDate) ?: new \DateTime,
            $invoice->currency,
        );

        // Do not set BT-23 here — horstoeko profile defaults (Peppol on XRechnung 3; null on EN16931).
        $buyerRef = $invoice->customerReference ?: $invoice->customerNumber ?: 'N/A';
        $doc->setDocumentBuyerReference($buyerRef);
    }

    private function setDocumentNotes(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        foreach ($invoice->documentNotes as $note) {
            $doc->addDocumentNote($note);
        }
    }

    // ─── Seller (BG-4) ──────────────────────────────────────────

    private function setSeller(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $doc->setDocumentSeller($invoice->supplierName);

        if ($invoice->supplierAddress === null) {
            throw new IncompleteInvoiceException('Missing required field: supplierAddress (BG-5 seller postal address).');
        }

        [$s1, $s2, $s3] = $this->buildAddressLines($invoice->supplierAddress);
        $doc->setDocumentSellerAddress(
            $s1,
            $s2,
            $s3,
            $invoice->supplierAddress->zip ?? '',
            $invoice->supplierAddress->city ?? '',
            $invoice->supplierAddress->country ?? '',
        );

        if ($invoice->supplierEmail === null || trim($invoice->supplierEmail) === '') {
            throw new IncompleteInvoiceException('Missing required field: supplierEmail (BT-34 seller electronic address).');
        }

        $doc->setDocumentSellerContact(
            $invoice->agent ?? '',
            '',
            $invoice->supplierPhone ?? '',
            '',
            $invoice->supplierEmail,
        );

        $doc->setDocumentSellerCommunication('EM', $invoice->supplierEmail);

        if ($invoice->supplierVatId) {
            $doc->addDocumentSellerTaxRegistration('VA', $invoice->supplierVatId);
        }
        if ($invoice->supplierTaxNumber) {
            $doc->addDocumentSellerTaxRegistration('FC', $invoice->supplierTaxNumber);
        }
    }

    // ─── Buyer (BG-7) ───────────────────────────────────────────

    private function setBuyer(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $doc->setDocumentBuyer($invoice->customerName);

        if ($invoice->customerAddress === null) {
            throw new IncompleteInvoiceException('Missing required field: customerAddress (BG-8 buyer postal address).');
        }

        [$b1, $b2, $b3] = $this->buildAddressLines($invoice->customerAddress);
        $doc->setDocumentBuyerAddress(
            $b1,
            $b2,
            $b3,
            $invoice->customerAddress->zip ?? '',
            $invoice->customerAddress->city ?? '',
            $invoice->customerAddress->country ?? '',
        );

        if ($invoice->customerVatId) {
            $doc->addDocumentBuyerTaxRegistration('VA', $invoice->customerVatId);
        }

        $doc->setDocumentBuyerCommunication('EM', $invoice->customerNumber ?: 'N/A');
    }

    private function setDelivery(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $deliveryDate = FlexibleDateParser::parse($invoice->deliveryDate);
        if ($deliveryDate !== null) {
            $doc->setDocumentSupplyChainEvent($deliveryDate);
        }

        [$shipToName, $shipToAddress] = $this->resolveEffectiveShipTo($invoice);

        $omitDuplicate = ShipToPartyEquality::equals(
            $shipToName,
            $shipToAddress,
            $invoice->customerName,
            $invoice->customerAddress,
        );

        $forceDeliverToForIntraCommunity = strtoupper(trim($invoice->vatCategoryCode)) === 'K';

        if ($omitDuplicate && ! $forceDeliverToForIntraCommunity) {
            return;
        }

        $trimmedName = $shipToName !== null ? trim($shipToName) : '';
        $address = $shipToAddress;
        $country = $address !== null ? trim((string) ($address->country ?? '')) : '';
        $hasName = $trimmedName !== '';
        $hasCountry = $address !== null && $country !== '';

        // BR-IC-12: VAT K still needs a full BG-15; buyer postal is acceptable when nothing else exists.
        if (! $hasName && ! $hasCountry && $forceDeliverToForIntraCommunity) {
            $shipToName = $invoice->customerName;
            $shipToAddress = $invoice->customerAddress;
            $trimmedName = $shipToName !== null ? trim($shipToName) : '';
            $address = $shipToAddress;
            $country = $address !== null ? trim((string) ($address->country ?? '')) : '';
            $hasName = $trimmedName !== '';
            $hasCountry = $address !== null && $country !== '';
        }

        if (! $hasName && ! $hasCountry) {
            return;
        }

        $doc->setDocumentShipTo($hasName ? $trimmedName : null);

        if ($hasCountry) {
            [$lineOne, $lineTwo, $lineThree] = $this->buildAddressLines($address);
            $doc->setDocumentShipToAddress(
                $lineOne,
                $lineTwo,
                $lineThree,
                $address->zip ?? '',
                $address->city ?? '',
                $address->country ?? '',
            );
        }
    }

    /**
     * @return array{0: ?string, 1: ?ZugferdAddress}
     */
    private function resolveEffectiveShipTo(ZugferdInvoice $invoice): array
    {
        $headerName = $invoice->shipToName;
        $headerAddress = $invoice->shipToAddress;
        $trimmedHeaderName = $headerName !== null ? trim($headerName) : '';
        $headerCountry = $headerAddress !== null ? trim((string) ($headerAddress->country ?? '')) : '';

        if ($trimmedHeaderName !== '' || $headerCountry !== '') {
            return [$trimmedHeaderName !== '' ? $trimmedHeaderName : null, $headerAddress];
        }

        return $this->promotedShipToFromLines($invoice);
    }

    /**
     * When header consignee is empty and every line shares one ship-to party that is not the buyer,
     * promote that party to document BG-13 (ADR 0020).
     *
     * @return array{0: ?string, 1: ?ZugferdAddress}
     */
    private function promotedShipToFromLines(ZugferdInvoice $invoice): array
    {
        $candidateName = null;
        $candidateAddress = null;
        $seen = false;

        foreach ($invoice->lines as $line) {
            $name = $line->shipToName;
            $address = $line->shipToAddress;
            $trimmed = is_string($name) ? trim($name) : '';
            $country = $address !== null ? trim((string) ($address->country ?? '')) : '';
            if ($trimmed === '' && $country === '') {
                return [null, null];
            }

            $effectiveName = $trimmed !== '' ? $trimmed : null;

            if (! $seen) {
                $candidateName = $effectiveName;
                $candidateAddress = $address;
                $seen = true;

                continue;
            }

            if (! ShipToPartyEquality::equals($candidateName, $candidateAddress, $effectiveName, $address)) {
                return [null, null];
            }
        }

        if (! $seen) {
            return [null, null];
        }

        if (ShipToPartyEquality::equals(
            $candidateName,
            $candidateAddress,
            $invoice->customerName,
            $invoice->customerAddress,
        )) {
            return [null, null];
        }

        return [$candidateName, $candidateAddress];
    }

    private function setTradeReferences(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $orderRef = $invoice->purchaseOrderReference !== null ? trim($invoice->purchaseOrderReference) : '';
        if ($orderRef !== '') {
            // IssueDate forbidden in core EN 16931 (UBL-CR-018).
            $doc->setDocumentBuyerOrderReferencedDocument($orderRef, null);
        }

        $despatch = $invoice->despatchAdviceReference !== null ? trim($invoice->despatchAdviceReference) : '';
        if ($despatch === '') {
            $despatch = $this->commonLineDeliveryNoteNumber($invoice) ?? '';
        }
        if ($despatch !== '') {
            $doc->setDocumentDespatchAdviceReferencedDocument($despatch, null);
        }
    }

    private function commonLineDeliveryNoteNumber(ZugferdInvoice $invoice): ?string
    {
        $candidate = null;
        foreach ($invoice->lines as $line) {
            $value = $line->deliveryNoteNumber !== null ? trim($line->deliveryNoteNumber) : '';
            if ($value === '') {
                continue;
            }
            if ($candidate === null) {
                $candidate = $value;

                continue;
            }
            if ($candidate !== $value) {
                return null;
            }
        }

        return $candidate;
    }

    private function emitLinePurchaseOrderLineReference(
        ZugferdDocumentBuilder $doc,
        ZugferdInvoice $invoice,
        ZugferdInvoiceLine $line,
    ): void {
        $lineId = $line->purchaseOrderLineReference !== null ? trim($line->purchaseOrderLineReference) : '';
        if ($lineId === '') {
            return;
        }

        $issuerAssignedId = $invoice->purchaseOrderReference !== null
            ? trim($invoice->purchaseOrderReference)
            : '';

        $doc->setDocumentPositionBuyerOrderReferencedDocument($issuerAssignedId, $lineId);
    }

    private function emitLineProductFacts(ZugferdDocumentBuilder $doc, ZugferdInvoiceLine $line): void
    {
        foreach ($line->itemAttributes as $attribute) {
            $name = trim($attribute->name);
            $value = trim($attribute->value);
            if ($name === '' || $value === '') {
                continue;
            }
            $doc->addDocumentPositionProductCharacteristic($name, $value);
        }

        foreach ($line->itemClassifications as $classification) {
            $code = trim($classification->code);
            $scheme = trim($classification->schemeId);
            if ($code === '' || $scheme === '') {
                continue;
            }
            $doc->addDocumentPositionProductClassification(
                $code,
                null,
                $scheme,
                $classification->schemeVersionId,
            );
        }
    }

    private function emitLineShipToAndReferenceNotes(
        ZugferdDocumentBuilder $doc,
        ZugferdInvoice $invoice,
        ZugferdInvoiceLine $line,
    ): void {
        $parts = [];

        [$effectiveName, $effectiveAddress] = $this->resolveEffectiveShipTo($invoice);
        $baselineName = $effectiveName;
        $baselineAddress = $effectiveAddress;
        if ($baselineName === null && $baselineAddress === null) {
            $baselineName = $invoice->customerName;
            $baselineAddress = $invoice->customerAddress;
        }

        $lineName = $line->shipToName;
        $lineAddress = $line->shipToAddress;
        $lineTrimmed = is_string($lineName) ? trim($lineName) : '';
        $lineCountry = $lineAddress !== null ? trim((string) ($lineAddress->country ?? '')) : '';
        $hasLineShipTo = $lineTrimmed !== '' || $lineCountry !== '';

        if ($hasLineShipTo && ! ShipToPartyEquality::equals(
            $lineTrimmed !== '' ? $lineTrimmed : null,
            $lineAddress,
            $baselineName,
            $baselineAddress,
        )) {
            $parts[] = $this->formatConsigneeNote($lineTrimmed !== '' ? $lineTrimmed : null, $lineAddress);
        }

        $headerOrder = $invoice->purchaseOrderReference !== null ? trim($invoice->purchaseOrderReference) : '';
        $lineOrderDoc = $line->orderDocumentReference !== null ? trim($line->orderDocumentReference) : '';
        if ($lineOrderDoc !== '' && $lineOrderDoc !== $headerOrder) {
            $parts[] = 'Purchase order: '.$lineOrderDoc;
        }

        $lineOrderDate = $line->purchaseOrderDate !== null ? trim($line->purchaseOrderDate) : '';
        if ($lineOrderDate !== '') {
            $parts[] = 'Order date: '.$lineOrderDate;
        }

        $commonDn = $this->commonLineDeliveryNoteNumber($invoice);
        $lineDn = $line->deliveryNoteNumber !== null ? trim($line->deliveryNoteNumber) : '';
        if ($lineDn !== '' && ($commonDn === null || $lineDn !== $commonDn)) {
            $parts[] = 'Despatch advice: '.$lineDn;
        }

        $note = trim(implode('; ', array_filter($parts)));
        if ($note !== '') {
            $doc->setDocumentPositionNote($note);
        }
    }

    private function formatConsigneeNote(?string $name, ?ZugferdAddress $address): string
    {
        $chunks = [];
        if ($name !== null && trim($name) !== '') {
            $chunks[] = trim($name);
        }
        if ($address !== null) {
            [$l1, $l2, $l3] = $this->buildAddressLines($address);
            foreach ([$l1, $l2, $l3, $address->zip ?? '', $address->city ?? '', $address->country ?? ''] as $part) {
                $part = trim((string) $part);
                if ($part !== '') {
                    $chunks[] = $part;
                }
            }
        }

        return 'Consignee: '.implode(', ', $chunks);
    }

    private function emitLineAllowanceCharges(ZugferdDocumentBuilder $doc, ZugferdInvoiceLine $line): void
    {
        foreach ($line->allowanceCharges as $item) {
            if ($item->amount <= 0) {
                continue;
            }
            $doc->addDocumentPositionAllowanceCharge(
                $item->amount,
                $item->isCharge,
                $item->percentage,
                $item->basisAmount,
                $item->reasonCode,
                $item->reasonText,
            );
        }
    }
    // ─── Payment (BG-16) ────────────────────────────────────────

    private function setPaymentInfo(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        if ($invoice->bankAccounts === []) {
            throw new IncompleteInvoiceException('Missing required field: bankAccounts (at least one payment means bank account).');
        }

        $paymentMeansCode = trim((string) $invoice->paymentMeansCode);
        if ($paymentMeansCode === '') {
            throw new IncompleteInvoiceException('Missing required field: paymentMeansCode (BT-81).');
        }

        foreach ($invoice->bankAccounts as $account) {
            $iban = trim($account->iban);
            if ($iban === '') {
                throw new IncompleteInvoiceException('Missing required field: bankAccounts[].iban (payment means payee IBAN).');
            }

            $doc->addDocumentPaymentMean(
                $paymentMeansCode,
                null,
                null,
                null,
                null,
                null,
                $iban,
                $account->accountHolder ?? $invoice->supplierName,
                null,
                $account->bic,
            );
        }

        // Payment terms
        if ($invoice->dueDate) {
            $dueDate = \DateTime::createFromFormat('Y-m-d', $invoice->dueDate);
            $termText = ($invoice->paymentTerms ?? '')
                .'; zahlbar ohne Abzug bis zum '.date('d.m.Y', strtotime($invoice->dueDate));
            if ($dueDate) {
                $doc->addDocumentPaymentTerm($termText, $dueDate);
            }
        } elseif ($invoice->paymentTerms) {
            $doc->addDocumentPaymentTerm($invoice->paymentTerms);
        }
    }

    // ─── Line Items ──────────────────────────────────────────────

    private function addLineItems(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice, string $profileKey): void
    {
        $emitLineActualDelivery = $profileKey === 'EXTENDED';

        foreach ($invoice->lines as $line) {
            $doc->addNewPosition((string) $line->position);
            $doc->setDocumentPositionProductDetails(
                $line->description,
                $line->descriptionDetail ?? '',
                $line->articleNumber,
            );
            $doc->setDocumentPositionNetPrice($line->unitPrice);
            $doc->setDocumentPositionQuantity(
                $line->quantity,
                $line->unitCode,
            );

            // Line total WITHOUT surcharges (surcharges go to document level)
            $doc->setDocumentPositionLineSummation($line->lineTotal);

            $doc->addDocumentPositionTax($invoice->vatCategoryCode, 'VAT', $invoice->vatRate);

            $this->setLineDeliveryDate($doc, $line->deliveryDate, $emitLineActualDelivery);
            $this->emitLinePurchaseOrderLineReference($doc, $invoice, $line);
            $this->emitLineProductFacts($doc, $line);
            $this->emitLineShipToAndReferenceNotes($doc, $invoice, $line);
            $this->emitLineAllowanceCharges($doc, $line);
        }
    }

    private function setLineDeliveryDate(
        ZugferdDocumentBuilder $doc,
        ?string $deliveryDate,
        bool $emitLineActualDelivery,
    ): void {
        $parsed = FlexibleDateParser::parse($deliveryDate);
        if ($parsed === null) {
            return;
        }

        if ($emitLineActualDelivery) {
            $doc->setDocumentPositionSupplyChainEvent($parsed);

            return;
        }

        $doc->setDocumentPositionBillingPeriod($parsed, $parsed);
    }

    // ─── Allowances & Charges (BG-20/BG-21) ─────────────────────

    private function addAllowanceCharges(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        foreach ($this->collectAllowanceCharges($invoice) as $item) {
            if ($item->amount <= 0) {
                continue;
            }

            $doc->addDocumentAllowanceCharge(
                $item->amount,
                $item->isCharge,
                $invoice->vatCategoryCode,
                'VAT',
                $invoice->vatRate,
                null,
                null,
                null,
                null,
                null,
                $item->reasonCode,
                $item->reasonText,
            );
        }
    }

    /**
     * @return list<ZugferdAllowanceCharge>
     */
    private function collectAllowanceCharges(ZugferdInvoice $invoice): array
    {
        return $invoice->allowanceCharges;
    }

    // ─── Totals (BG-22) ─────────────────────────────────────────

    private function setTotals(ZugferdDocumentBuilder $doc, ZugferdInvoice $invoice): void
    {
        $lineTotalSum = 0;
        foreach ($invoice->lines as $line) {
            $lineTotalSum += $line->lineTotal;
        }

        $chargeTotal = 0.0;
        $allowanceTotal = 0.0;

        foreach ($this->collectAllowanceCharges($invoice) as $item) {
            if ($item->amount <= 0) {
                continue;
            }

            if ($item->isCharge) {
                $chargeTotal += $item->amount;
            } else {
                $allowanceTotal += $item->amount;
            }
        }

        foreach ($invoice->lines as $line) {
            foreach ($line->allowanceCharges as $item) {
                if ($item->amount <= 0) {
                    continue;
                }

                if ($item->isCharge) {
                    $chargeTotal += $item->amount;
                } else {
                    $allowanceTotal += $item->amount;
                }
            }
        }

        $doc->setDocumentSummation(
            $invoice->grossTotal,          // grandTotalAmount (BT-112)
            $invoice->grossTotal,          // duePayableAmount (BT-115)
            $lineTotalSum,                 // lineTotalAmount (BT-106)
            $chargeTotal,                  // chargeTotalAmount (BT-108)
            $allowanceTotal,               // allowanceTotalAmount (BT-107)
            $invoice->netTotal,            // taxBasisTotalAmount (BT-109)
            $invoice->vatAmount,           // taxTotalAmount (BT-110)
        );

        $doc->addDocumentTax($invoice->vatCategoryCode, 'VAT', $invoice->netTotal, $invoice->vatAmount, $invoice->vatRate);
    }

    // ─── Helper functions ─────────────────────────────────────────

    /**
     * @return array{0: ?string, 1: ?string, 2: ?string}
     */
    private function buildAddressLines(ZugferdAddress $address): array
    {
        return [$address->street, $address->addressLine2, $address->addressLine3];
    }
}
