export function createDefaultEditorState(blockTypes) {
    return {
        blocks: [],
        selectedBlockId: null,
        draggingBlockId: null,
        showToolbar: false,
        blockIdCounter: 0,
        dragStartIndex: null,
        dragOverIndex: null,
        showSidebar: false,
        blockSettingsCache: {},
        blockSettingsVersion: 0,
        showImportModal: false,
        importJSONText: '',
        importJSONValid: false,
        importJSONError: null,
        importJSONPreview: null,
        showImageSettingsModal: false,
        imageSettingsBlockId: null,
        imageSettingsUrl: '',
        imageSettingsOriginalUrl: '',
        imageSettingsMediaUsables: [],
        imageSettingsOriginalMediaUsables: [],
        imageSettingsAlt: '',
        imageSettingsTitle: '',
        imageSettingsActiveTab: 'library',
        showVideoSettingsModal: false,
        videoSettingsBlockId: null,
        videoSettingsUrl: '',
        videoSettingsPoster: '',
        videoSettingsTitle: '',
        videoSettingsActiveTab: 'library',
        showEmbedSettingsModal: false,
        embedSettingsBlockId: null,
        embedSettingsUrl: '',
        embedSettingsTitle: '',
        mediaLibraryApiUrl: '/api/media',
        mediaLibraryCollection: null,
        mediaUsableType: '',
        mediaUsableId: '',
        mediaLibraryItems: [],
        mediaLibraryLoading: false,
        mediaLibraryError: '',
        mediaLibrarySearch: '',
        mediaLibraryType: 'image',
        mediaLibraryTarget: null,
        mediaLibraryDebounceTimeout: null,
        mediaLibraryCache: new Map(),
        mediaLibraryPendingRequests: new Map(),
        mediaLibraryPage: 1,
        mediaLibraryPerPage: 25,
        mediaLibraryTotalPages: 1,
        mediaLibraryTotalItems: 0,
        mediaLibrarySelectedUrl: '',
        mediaLibraryRecentlyUploadedUrl: '',
        mediaUploadLoading: false,
        mediaUploadError: '',
        mediaUploadLanguage: '',
        mediaUploadMaxFileSizeKb: null,
        mediaUploadProgressPercent: 0,
        mediaUploadProcessing: false,
        mediaUploadFileName: '',
        mediaUploadFileSizeLabel: '',
        showFloatingToolbar: false,
        floatingToolbarPosition: { top: 0, left: 0 },
        selectedText: '',
        selectedRange: null,
        showLinkModal: false,
        linkModal: {
            type: null,
            blockId: null,
            url: '',
            target: '_blank',
            text: '',
            element: null,
            range: null,
            markerIds: null
        },
        childBlockTypes: blockTypes,
        notification: {
            show: false,
            message: '',
            type: 'success',
            duration: 3000
        },
        notificationTimeout: null,
        showConfirmModal: false,
        confirmModal: {
            title: '',
            message: '',
            onConfirm: null,
            onCancel: null,
            onExtend: null,
            showExtend: false,
            showLinkFollow: false,
            linkFollowUrl: null,
            linkFollowTarget: '_self'
        },
        textSelectionTimeout: null,
        elementCache: new Map(),
        eventListeners: [],
        templates: null,
        updateBlockContentTimeouts: new Map(),
        inlineContentBuffer: new Map(),
        inlineContentDebounceMs: 400,
        validateJSONTimeout: null,
        renderBlockCache: new Map(),
        renderChildCache: new Map(),
        jsonDisplayCache: '',
        jsonDisplayTimeout: null,
        jsonDisplayHash: '',
        blockLookupCache: new Map(),
        blockLookupCacheVersion: 0
    };
}
