name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - "feature/**"

jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    outputs:
      artifact-name: app-artifact
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Bootstrap Laravel App
        run: |
          php ci.php
          mkdir -p storage/app storage/framework storage/logs
          touch storage/.gitkeep
          touch database/database.sqlite

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: |
            .env
            artisan
            app
            bootstrap
            config
            database
            public
            routes
            storage
            tests
            vendor
            composer.*
            phpunit.xml
            clover.xml

  pest:
    name: Run Pest Tests PHP ${{ matrix.php }} on ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    env:
      DB_DATABASE: testing
      DB_PASSWORD: secretroot
      APP_KEY: base64:1NxfrNErQ0vo1ZnPcLeVhnE7tOZdKlKiFORzPA92krM=

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: secretroot
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Download App Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer

      - name: Set permissions (Linux only)
        if: runner.os == 'Linux'
        run: |
          chmod -R 755 storage bootstrap || echo "Permission fix skipped"

      - name: Run Pest Tests
        run: vendor/bin/pest --coverage-clover=clover.xml
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: secretroot

  phpstan:
    name: Run PHPStan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download App Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

  codacy:
    name: Send Coverage to Codacy
    needs: pest
    runs-on: ubuntu-latest
    if: ${{ secrets.CODACY != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download App Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact

      - name: Upload to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          api-token: ${{ secrets.CODACY }}
          coverage-reports: clover.xml

  codeclimate:
    name: Send Coverage to Code Climate
    needs: pest
    runs-on: ubuntu-latest
    if: ${{ secrets.CC_TEST_REPORTER_ID != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download App Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact

      - name: Upload to Code Climate
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: vendor/bin/pest --coverage-clover clover.xml
