name: Cleanup Empty Translations

on:
  pull_request:
    branches: [ "main" ]

jobs:
  remove-empty-translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Run cleanup script
        run: php .github/scripts/cleanup-empty-translations.php

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          push_options: --force
          commit_message: Cleanup translations
