name: Contributions

on:
  push:
    branches:
      - dev

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: Add contributors to READMEs
        steps:
            - name: Contributors in Monorepo
              uses: akhilmhdh/contributors-readme-action@v2.3.6
              with:
                readme_path: "README.md"
                use_username: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Contributors in app-components
              uses: akhilmhdh/contributors-readme-action@v2.3.6
              with:
                readme_path: "_components/tallui-app-components/README.md"
                use_username: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
