name: Contributions

on:
  push:
    branches:
      - main

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Add contributors to READMEs
    steps:
      - name: Contributors in Monorepo
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          readme_path: "README.md"
          use_username: true
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}
