name: "Split Packages"

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.BOT }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - audit
          - builder
          - core
          - expiry
          - flags
          - jobs
          - locate
          - login-link
          - notifications
          - passkey
          - permission
          - press
          - security
          - sync
          - redis-model
          - trainings
          - user
          - user-device
          - user-session

    steps:
      - uses: actions/checkout@v4

      # Fetch all tags to get the latest tag for moox/core
      - name: Fetch all tags
        run: git fetch --tags

      # Get the latest tag for moox/core (you can adjust this command as needed to fit your tagging convention)
      - name: Get latest moox/core version
        id: get_core_version
        run: |
          latest_tag=$(git tag --list "core-*" --sort=-v:refname | head -n 1 | sed 's/core-//')
          echo "core_version=$latest_tag" >> $GITHUB_ENV

      # Update composer.json with the latest moox/core version
      - name: Update moox/core version in composer.json
        working-directory: packages/${{ matrix.package }}
        run: |
          if [ -f composer.json ]; then
            core_version=${{ env.core_version }}
            # Update moox/core version in composer.json
            sed -i 's/"moox\/core": "\*"/"moox\/core": "^'$core_version'"/' composer.json
          fi

      # Commit the updated composer.json with the new version
      - name: Commit changes
        working-directory: packages/${{ matrix.package }}
        run: |
          if [ -f composer.json ]; then
            git config --global user.name "mooxbot"
            git config --global user.email "bot@moox.org"
            git add composer.json
            git commit -m "Update moox/core dependency to ^${{ env.core_version }}"
          fi

      # Split the package to its respective repository
      - name: Split the package
        uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: "packages/${{ matrix.package }}"

          repository_organization: "mooxphp"
          repository_name: "${{ matrix.package }}"

          user_name: "mooxbot"
          user_email: "bot@moox.org"
