name: "Split Packages"

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.BOT }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - core
          - builder
          - jobs
          - user
          - user-device
          - user-session
          - login-link
          - sync
          - audit
          - passkey
          - notifications
          - flags
          - locate

    steps:
      - uses: actions/checkout@v4

      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@v2.3.0"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: "packages/${{ matrix.package }}"

          repository_organization: "mooxphp"
          repository_name: "${{ matrix.package }}"

          user_name: "mooxbot"
          user_email: "bot@moox.org"
