name: "Split Packages"

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.BOT }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - audit
          - builder
          - core
          - expiry
          - flags
          - jobs
          - locate
          - login-link
          - notifications
          - passkey
          - permission
          - press
          - security
          - sync
          - redis-model
          - trainings
          - user
          - user-device
          - user-session

    steps:
      - uses: actions/checkout@v4

      # Modify the composer.json for each package to update the moox/core version
      - name: Update core version in composer.json
        working-directory: packages/${{ matrix.package }}
        run: |
          if [ -f composer.json ]; then
            core_version=${{ env.core_version }}
            echo "Updating moox/core version to $core_version in ${{ matrix.package }}"
            jq '.require["moox/core"] = "^2.1.0"' composer.json > tmp.$$.json && mv tmp.$$.json composer.json
          fi

      # Commit the updated composer.json (if there was a change)
      - name: Commit changes
        working-directory: packages/${{ matrix.package }}
        run: |
          if [ -f composer.json ]; then
            git config --global user.name "mooxbot"
            git config --global user.email "bot@moox.org"
            git add composer.json
            git commit -m "Update moox/core dependency to ^2.1.0" || echo "No changes to commit"
          fi

      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@v2.3.0"
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: "packages/${{ matrix.package }}"

          repository_organization: "mooxphp"
          repository_name: "${{ matrix.package }}"

          user_name: "mooxbot"
          user_email: "bot@moox.org"
