name: "Split Packages"

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.BOT }}

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      core_version: ${{ steps.get-core-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          PACKAGES=$(jq -c '{package: [.packages[].name]}' .github/workflows/moox.json)
          echo "matrix=$PACKAGES" >> $GITHUB_OUTPUT
      - id: get-core-version
        run: |
          VERSION=$(jq -r '.packages[] | select(.name == "core") | .latest' .github/workflows/moox.json)
          echo "version=^${VERSION}" >> $GITHUB_OUTPUT

  packages_split:
    needs: matrix_prep
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Replace core version in composer.json
        working-directory: packages/${{ matrix.package }}
        run: |
          if [ -f composer.json ]; then
            echo "Updating moox/core version in ${{ matrix.package }}"
            sed -i 's/"moox\/core": "\*"/"moox\/core": "${{ needs.matrix_prep.outputs.core_version }}"/g' composer.json
          fi

      - name: Commit changes
        working-directory: packages/${{ matrix.package }}
        run: |
          if [ -f composer.json ]; then
            git config --global user.name "mooxbot"
            git config --global user.email "bot@moox.org"
            git add composer.json
            git commit -m "Update moox/core dependency to ${{ needs.matrix_prep.outputs.core_version }}" || echo "No changes to commit"
          fi

      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@v2.3.0"
        with:
          package_directory: "packages/${{ matrix.package }}"
          repository_organization: "mooxphp"
          repository_name: "${{ matrix.package }}"
          user_name: "mooxbot"
          user_email: "bot@moox.org"
