name: "Split Packages"

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.BOT }}

jobs:
  load-config:
    runs-on: ubuntu-latest
    outputs:
      core_version: ${{ steps.set-vars.outputs.core_version }}
      packages: ${{ steps.set-vars.outputs.packages }}

    steps:
      - uses: actions/checkout@v4

      # Read and parse moox.json
      - id: set-vars
        run: |
          core_version=$(jq -r '.core_version' moox.json)
          packages=$(jq -r '.packages | join(",")' moox.json)

          echo "CORE_VERSION=${core_version}" >> $GITHUB_ENV
          echo "PACKAGES=${packages}" >> $GITHUB_ENV

          echo "::set-output name=core_version::$core_version"
          echo "::set-output name=packages::$packages"

  packages_split:
    runs-on: ubuntu-latest
    needs: load-config

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.load-config.outputs.packages) }}

    steps:
      - uses: actions/checkout@v4

      # Search and replace "moox/core": "*" with "moox/core": "^2.1.0" in composer.json
      - name: Replace core version in composer.json
        working-directory: packages/${{ matrix.package }}
        run: |
          if [ -f composer.json ]; then
            echo "Updating moox/core version in ${{ matrix.package }}"
            sed -i 's/"moox\/core": "\*"/"moox\/core": "^${{ env.CORE_VERSION }}"/g' composer.json
          fi

      # Commit the updated composer.json (if there was a change)
      - name: Commit changes
        working-directory: packages/${{ matrix.package }}
        run: |
          if [ -f composer.json ]; then
            git config --global user.name "mooxbot"
            git config --global user.email "bot@moox.org"
            git add composer.json
            git commit -m "Update moox/core dependency to ^${{ env.CORE_VERSION }}" || echo "No changes to commit"
          fi

      # Split the package to its respective repository
      - name: Split package repository
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: symplify/monorepo-split-github-action@v2.3.0
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: "packages/${{ matrix.package }}"
          repository_organization: "mooxphp"
          repository_name: "${{ matrix.package }}"
          user_name: "mooxbot"
          user_email: "bot@moox.org"
