name: 'Split Components'

on:
    push:
        branches:
            - main
        tags:
            - '*'

env:
    GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}

jobs:
    packages_split:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                package:
                  - tallui-web-components
                  - tallui-form-components
                  - tallui-app-components
                  - tallui-dev-components
        steps:
            -   uses: actions/checkout@v3

            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                uses: "symplify/monorepo-split-github-action@2.2"
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    package_directory: '_components/${{ matrix.package }}'

                    repository_organization: 'usetall'
                    repository_name: '${{ matrix.package }}'

                    user_name: "tallui-bot"
                    user_email: "bot@tallui.io"
